[workspace]
members = [
    "contracts/audit",
    "contracts/asset",
    "contracts/rebalancing",
    "contracts/events",
    "contracts/staking",
    "contracts/fee",
    "contracts/gamification",
    "contracts/emergency",
    "contracts/pricefeed",
    "contracts/valuation",
    "contracts/versioning",
    "contracts/governance",
    "contracts/trade",
    "contracts/prediction",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["AstraPort"]
license = "Apache-2.0"

[workspace.dependencies]
soroban-sdk = "=21.5.0"
soroban-contract = "=21.5.0"



[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
