[package]
name = "astraport-rebalancing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]

[dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
astraport-audit = { path = "../audit" }
astraport-trade = { path = "../trade" }
astraport-pricefeed = { path = "../pricefeed" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
