[package]
name = "astraport-trade"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
astraport-audit = { path = "../audit" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
